providers:
  docker:
    defaultRule: 'Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)'
    network: launchroom_net

api:
  insecure: true

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

accessLog: {}
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    headerLabels:
      useragent: 'User-Agent'
      xforwardedhost: 'X-Forwarded-Host'
      xrequestpath: 'X-Replaced-Path'

# Let's Encrypt certificate resolver configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: 'launchroom@example.com'
      storage: '/etc/traefik/acme/acme.json'
      httpChallenge:
        entryPoint: web

http:
  middlewares:
    addPathToMetrics:
      replacePathRegex:
        regex: '^/(.*)'
        replacement: '/$1'
